kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: repd-us-central1-b-c
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: us-central1-b, us-central1-c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pv-claim
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 200Gi